<?php

/**
 * @file
 * Contains eventridho.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\eventridho\Event\UserLoginEvent;

/**
 * Implements hook_user_login().
 */
function custom_events_user_login($account) {
  // Instantiate our event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher server and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(UserLoginEvent::EVENT_NAME, $event);
}

/**
 * Implements hook_help().
 */
function eventridho_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eventridho module.
    case 'help.page.eventridho':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function eventridho_theme() {
  return [
    'eventridho' => [
      'render element' => 'children',
    ],
  ];
}
